"use strict";

module.exports = {
  // power commands
  "powerOn": {command: 'power_on!', response: 'power', delimiter: '_', sized: false},
  "powerOff": {command: 'power_off!', response: 'power', delimiter: '_', sized: false},
  "powerToggle": {command: 'power_toggle!', response: 'power', delimiter: '_', sized: false},
  // volume commands
  "volumeUp": {command: 'volume_up!', response: 'volume', delimiter: '=', sized: false},
  "volumeDown": {command: 'volume_down!', response: 'volume', delimiter: '=', sized: false},
  "volumeMax": {command: 'volume_max!', response: 'volume', delimiter: '=', sized: false},
  "volumeMin": {command: 'volume_min!', response: 'volume', delimiter: '=', sized: false},
  // volume_n!: implemented directly
  "muteToggle": {command: 'mute!', response: 'mute', delimiter: '=', sized: false},
  "muteOn": {command: 'mute_on!', response: 'mute', delimiter: '=', sized: false},
  "muteOff": {command: 'mute_off!', response: 'mute', delimiter: '=', sized: false},
  // source commands
  "rcd": {command: 'rcd!', response: 'source', delimiter: '=', sized: false},
  "cd": {command: 'cd!', response: 'source', delimiter: '=', sized: false},
  "coax1": {command: 'coax1!', response: 'source', delimiter: '=', sized: false},
  "coax2": {command: 'coax2!', response: 'source', delimiter: '=', sized: false},
  "optical1": {command: 'opt1!', response: 'source', delimiter: '=', sized: false},
  "optical2": {command: 'opt2!', response: 'source', delimiter: '=', sized: false},
  "aux1": {command: 'aux1!', response: 'source', delimiter: '=', sized: false},
  "aux2": {command: 'aux2!', response: 'source', delimiter: '=', sized: false},
  "tuner": {command: 'tuner!', response: 'source', delimiter: '=', sized: false},
  "phono": {command: 'phono!', response: 'source', delimiter: '=', sized: false},
  "usb": {command: 'usb!', response: 'source', delimiter: '=', sized: false},
  // tone commands
  "toneOn": {command: 'tone_on!', response: 'tone', delimiter: '=', sized: false},
  "toneOff": {command: 'tone_off!', response: 'tone', delimiter: '=', sized: false},
  "bassUp": {command: 'bass_up!', response: 'bass', delimiter: '=', sized: false},
  "bassDown": {command: 'bass_down!', response: 'bass', delimiter: '=', sized: false},
  "bassMin": {command: 'bass_-10!', response: 'bass', delimiter: '=', sized: false},
  "bassNeutral": {command: 'bass_000!', response: 'bass', delimiter: '=', sized: false},
  "BassMax": {command: 'bass_+10!', response: 'bass', delimiter: '=', sized: false},
  "trebleUp": {command: 'treble_up!', response: 'treble', delimiter: '=', sized: false},
  "trebleDown": {command: 'treble_down!', response: 'treble', delimiter: '=', sized: false},
  "trebleMin": {command: 'treble_-10!', response: 'treble', delimiter: '=', sized: false},
  "trebleNeutral": {command: 'treble_000!', response: 'treble', delimiter: '=', sized: false},
  "trebleMax": {command: 'treble_+10!', response: 'treble', delimiter: '=', sized: false},
  // balance commands
  "balanceRight": {command: 'balance_right!', response: 'balance', delimiter: '=', sized: false},
  "balanceLeft": {command: 'balance_left!', response: 'balance', delimiter: '=', sized: false},
  "balanceLeftMax": {command: 'balance_L15!', response: 'balance', delimiter: '=', sized: false},
  "balanceMiddle": {command: 'balance_000!', response: 'balance', delimiter: '=', sized: false},
  "balanceRightMax": {command: 'balance_R15!', response: 'balance', delimiter: '=', sized: false},
  // display refresh commands
  "displayUpdateAuto": {command: 'display_update_auto!', response: 'display_update', delimiter: '=', sized: false},
  "displayUpdateManual": {command: 'display_update_manual!', response: 'display_update', delimiter: '=', sized: false},
  // status request commands
  "getDisplay": {command: 'get_display!', response: 'display', delimiter: '=', sized: true},
  "getDisplay1": {command: 'get_display1!', response: 'display1', delimiter: '=', sized: true},
  "getDisplay2": {command: 'get_display2!', response: 'display2', delimiter: '=', sized: true},
  "getProductType": {command: 'get_product_type!', response: 'product_type', delimiter: '=', sized: true},
  "getProductVersion": {command: 'get_product_version!', response: 'product_version', delimiter: '=', sized: true},
  "getTcVersion": {command: 'get_tc_version!', response: 'tc_version', delimiter: '=', sized: true},
  "getDisplaySize": {command: 'get_display_size!', response: 'display_size', delimiter: '=', sized: false},
  "getDisplayUpdate": {command: 'get_display_update!', response: 'display_update', delimiter: '=', sized: false},
  "getCurrentPower": {command: 'get_current_power!', response: 'power', delimiter: '=', sized: false},
  "getCurrentSource": {command: 'get_current_source!', response: 'source', delimiter: '=', sized: false},
  "getTone": {command: 'get_tone!', response: 'tone', delimiter: '=', sized: false},
  "getBass": {command: 'get_bass!', response: 'bass', delimiter: '=', sized: false},
  "getTreble": {command: 'get_treble!', response: 'treble', delimiter: '=', sized: false},
  "getBalance": {command: 'get_balance!', response: 'balance', delimiter: '=', sized: false},
  "getCurrentFrequency": {command: 'get_current_freq!', response: 'freq', delimiter: '=', sized: false},
  "getPlayStatus": {command: 'get_play_status!', response: 'play_status', delimiter: '=', sized: false},
  "getVolumeMax": {command: 'get_volume_max!', response: 'volume_max', delimiter: '=', sized: false},
  "getVolumeMin": {command: 'get_volume_min!', response: 'volume_min', delimiter: '=', sized: false},
  "getVolume": {command: 'get_volume!', response: 'volume', delimiter: '=', sized: false},
  "getToneMax": {command: 'get_tone_max!', response: 'tone_max', delimiter: '=', sized: false}
};