"use strict";

module.exports = {
  // power commands
  "powerOn": {command: 'power_on!', response: 'power', delimiter: '_', doc: 'Power on'},
  "powerOff": {command: 'power_off!', response: 'power', delimiter: '_', doc: 'Power off'},
  "powerToggle": {command: 'power_toggle!', response: 'power', delimiter: '_', doc: 'Toggle power'},
  // volume commands
  "volumeUp": {command: 'volume_up!', response: 'volume', doc: 'Increase volume a bit'},
  "volumeDown": {command: 'volume_down!', response: 'volume', doc: 'Decrease volume a bit'},
  "volumeMax": {command: 'volume_max!', response: 'volume', doc: 'Set volume to maximum'},
  "volumeMin": {command: 'volume_min!', response: 'volume', doc: 'Set volume to minimum'},
  "volume": {command: 'volume_xx!', response: 'volume', param: 'amount', doc: 'Set volume to _amount_'},
  "muteToggle": {command: 'mute!', response: 'mute', doc: 'Toggle mute state'},
  "muteOn": {command: 'mute_on!', response: 'mute', doc: 'Mute'},
  "muteOff": {command: 'mute_off!', response: 'mute', doc: 'Unmute'},
  // source commands
  "rcd": {command: 'rcd!', response: 'source', doc: 'Set source to Rotel CD'},
  "cd": {command: 'cd!', response: 'source', doc: 'Set source to CD'},
  "coax1": {command: 'coax1!', response: 'source', doc: 'Set source to coax 1'},
  "coax2": {command: 'coax2!', response: 'source', doc: 'Set source to coax 2'},
  "optical1": {command: 'opt1!', response: 'source', doc: 'Set source to optical 1'},
  "optical2": {command: 'opt2!', response: 'source', doc: 'Set source to optical 2'},
  "aux1": {command: 'aux1!', response: 'source', doc: 'Set source to auxiliary 1'},
  "aux2": {command: 'aux2!', response: 'source', doc: 'Set source to auxiliary 2'},
  "tuner": {command: 'tuner!', response: 'source', doc: 'Set source to tuner'},
  "phono": {command: 'phono!', response: 'source', doc: 'Set source to phono'},
  "usb": {command: 'usb!', response: 'source', doc: 'Set source to usb (or bluetooth if dongle is installed)'},
  // tone commands
  "toneOn": {command: 'tone_on!', response: 'tone', doc: 'Switch tone controls on'},
  "toneOff": {command: 'tone_off!', response: 'tone', doc: 'Switch tone controls off'},
  "bassUp": {command: 'bass_up!', response: 'bass', doc: 'Increase bass a bit'},
  "bassDown": {command: 'bass_down!', response: 'bass', doc: 'Decrease bass a bit'},
  "bassMin": {command: 'bass_-10!', response: 'bass', doc: 'Set bass to minimum'},
  "bassNeutral": {command: 'bass_000!', response: 'bass', doc: 'Set bass to neutral'},
  "BassMax": {command: 'bass_+10!', response: 'bass', doc: 'Set bass to maximum'},
  "trebleUp": {command: 'treble_up!', response: 'treble', doc: 'Increase treble a bit'},
  "trebleDown": {command: 'treble_down!', response: 'treble', doc: 'Decrease treble a bit'},
  "trebleMin": {command: 'treble_-10!', response: 'treble', doc: 'Set treble to minimum'},
  "trebleNeutral": {command: 'treble_000!', response: 'treble', doc: 'Set treble to neutral'},
  "trebleMax": {command: 'treble_+10!', response: 'treble', doc: 'Set treble to maximum'},
  // balance commands
  "balanceRight": {command: 'balance_right!', response: 'balance', doc: 'Set balance a bit more to the right'},
  "balanceLeft": {command: 'balance_left!', response: 'balance', doc: 'Set balance a bit more to the left'},
  "balanceLeftMax": {command: 'balance_L15!', response: 'balance', doc: 'Set balance fully left'},
  "balanceMiddle": {command: 'balance_000!', response: 'balance', doc: 'Set balance in the middle'},
  "balanceRightMax": {command: 'balance_R15!', response: 'balance', doc: 'Set balance fully right'},
  // display refresh commands
  "displayUpdateAuto": {command: 'display_update_auto!', response: 'display_update', doc: 'Set display update to auto'},
  "displayUpdateManual": {command: 'display_update_manual!', response: 'display_update', doc: 'Set display update to manual'},
  // status request commands
  "getDisplay": {command: 'get_display!', response: 'display', sized: true, doc: 'Get what the display is currently showing'},
  "getDisplay1": {command: 'get_display1!', response: 'display1', sized: true, doc: 'Get line 1 of display'},
  "getDisplay2": {command: 'get_display2!', response: 'display2', sized: true, doc: 'Get line 2 of the display'},
  "getProductType": {command: 'get_product_type!', response: 'product_type', sized: true, doc: 'Get the product type'},
  "getProductVersion": {command: 'get_product_version!', response: 'product_version', sized: true, doc: 'Get the product version'},
  "getTcVersion": {command: 'get_tc_version!', response: 'tc_version', sized: true, doc: 'Get the TC version'},
  "getDisplaySize": {command: 'get_display_size!', response: 'display_size', doc: 'Get the display size'},
  "getDisplayUpdate": {command: 'get_display_update!', response: 'display_update', doc: 'Get the display update strategy'},
  "getCurrentPower": {command: 'get_current_power!', response: 'power', doc: 'Get the power status'},
  "getCurrentSource": {command: 'get_current_source!', response: 'source', doc: 'Get the selected source'},
  "getTone": {command: 'get_tone!', response: 'tone', doc: 'Get the tone control status'},
  "getBass": {command: 'get_bass!', response: 'bass', doc: 'Get the bass value'},
  "getTreble": {command: 'get_treble!', response: 'treble', doc: 'Get the treble value'},
  "getBalance": {command: 'get_balance!', response: 'balance', doc: 'Get the balance'},
  "getCurrentFrequency": {command: 'get_current_freq!', response: 'freq', doc: 'Get the sampling frequency'},
  "getPlayStatus": {command: 'get_play_status!', response: 'play_status', doc: 'Get the play status'},
  "getVolumeMax": {command: 'get_volume_max!', response: 'volume_max', doc: 'Get the maximum volume'},
  "getVolumeMin": {command: 'get_volume_min!', response: 'volume_min', doc: 'Get the minimum volume'},
  "getVolume": {command: 'get_volume!', response: 'volume', doc: 'Get the volume'},
  "getToneMax": {command: 'get_tone_max!', response: 'tone_max', doc: 'Get the maximum tone value'}
};