"use strict";

module.exports = {
  // power commands
  "powerOn": {command: 'power_on!', response: 'power', delimiter: '_'},
  "powerOff": {command: 'power_off!', response: 'power', delimiter: '_'},
  "powerToggle": {command: 'power_toggle!', response: 'power', delimiter: '_'},
  // volume commands
  "volumeUp": {command: 'volume_up!', response: 'volume'},
  "volumeDown": {command: 'volume_down!', response: 'volume'},
  "volumeMax": {command: 'volume_max!', response: 'volume'},
  "volumeMin": {command: 'volume_min!', response: 'volume'},
  // volume_n!: implemented directly
  "muteToggle": {command: 'mute!', response: 'mute'},
  "muteOn": {command: 'mute_on!', response: 'mute'},
  "muteOff": {command: 'mute_off!', response: 'mute'},
  // source commands
  "rcd": {command: 'rcd!', response: 'source'},
  "cd": {command: 'cd!', response: 'source'},
  "coax1": {command: 'coax1!', response: 'source'},
  "coax2": {command: 'coax2!', response: 'source'},
  "optical1": {command: 'opt1!', response: 'source'},
  "optical2": {command: 'opt2!', response: 'source'},
  "aux1": {command: 'aux1!', response: 'source'},
  "aux2": {command: 'aux2!', response: 'source'},
  "tuner": {command: 'tuner!', response: 'source'},
  "phono": {command: 'phono!', response: 'source'},
  "usb": {command: 'usb!', response: 'source'},
  // tone commands
  "toneOn": {command: 'tone_on!', response: 'tone'},
  "toneOff": {command: 'tone_off!', response: 'tone'},
  "bassUp": {command: 'bass_up!', response: 'bass'},
  "bassDown": {command: 'bass_down!', response: 'bass'},
  "bassMin": {command: 'bass_-10!', response: 'bass'},
  "bassNeutral": {command: 'bass_000!', response: 'bass'},
  "BassMax": {command: 'bass_+10!', response: 'bass'},
  "trebleUp": {command: 'treble_up!', response: 'treble'},
  "trebleDown": {command: 'treble_down!', response: 'treble'},
  "trebleMin": {command: 'treble_-10!', response: 'treble'},
  "trebleNeutral": {command: 'treble_000!', response: 'treble'},
  "trebleMax": {command: 'treble_+10!', response: 'treble'},
  // balance commands
  "balanceRight": {command: 'balance_right!', response: 'balance'},
  "balanceLeft": {command: 'balance_left!', response: 'balance'},
  "balanceLeftMax": {command: 'balance_L15!', response: 'balance'},
  "balanceMiddle": {command: 'balance_000!', response: 'balance'},
  "balanceRightMax": {command: 'balance_R15!', response: 'balance'},
  // display refresh commands
  "displayUpdateAuto": {command: 'display_update_auto!', response: 'display_update'},
  "displayUpdateManual": {command: 'display_update_manual!', response: 'display_update'},
  // status request commands
  "getDisplay": {command: 'get_display!', response: 'display', sized: true},
  "getDisplay1": {command: 'get_display1!', response: 'display1', sized: true},
  "getDisplay2": {command: 'get_display2!', response: 'display2', sized: true},
  "getProductType": {command: 'get_product_type!', response: 'product_type', sized: true},
  "getProductVersion": {command: 'get_product_version!', response: 'product_version', sized: true},
  "getTcVersion": {command: 'get_tc_version!', response: 'tc_version', sized: true},
  "getDisplaySize": {command: 'get_display_size!', response: 'display_size'},
  "getDisplayUpdate": {command: 'get_display_update!', response: 'display_update'},
  "getCurrentPower": {command: 'get_current_power!', response: 'power'},
  "getCurrentSource": {command: 'get_current_source!', response: 'source'},
  "getTone": {command: 'get_tone!', response: 'tone'},
  "getBass": {command: 'get_bass!', response: 'bass'},
  "getTreble": {command: 'get_treble!', response: 'treble'},
  "getBalance": {command: 'get_balance!', response: 'balance'},
  "getCurrentFrequency": {command: 'get_current_freq!', response: 'freq'},
  "getPlayStatus": {command: 'get_play_status!', response: 'play_status'},
  "getVolumeMax": {command: 'get_volume_max!', response: 'volume_max'},
  "getVolumeMin": {command: 'get_volume_min!', response: 'volume_min'},
  "getVolume": {command: 'get_volume!', response: 'volume'},
  "getToneMax": {command: 'get_tone_max!', response: 'tone_max'}
};